CREATE DATABASE GL;
USE GL;

CREATE TABLE employee(
id INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Email_id VARCHAR(50) NOT NULL,
Phone_Number VARCHAR(20) 
);

SELECT * FROM EMPLOYEE;

DROP TABLE EMPLOYEE;

DESC EMPLOYEE;